name: deployment
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Configure Git
      run: .ci/git-config.sh
    - name: Build and deploy
      run: make deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
