name: Quality
on:
  push:
    branches:
    - main
  schedule:
  - cron: "0 0 * * *"
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: make install
    - name: Check code quality
      run: make quality
